hash-format = "sha256"

[[files]]
file = "config/yosbr/config/NoChatReports/NCR-Client.json"
hash = "1c0e36f3124939575589c950dbdeed152cd3541e125562199aa6783af482aa50"

[[files]]
file = "config/yosbr/config/betterf3.json"
hash = "ef5ad04ddf4f81608b4efe290566555a70124d1bda3fc0e230854fbde1dcebd8"

[[files]]
file = "config/yosbr/config/fabrishot.properties"
hash = "daccbfe6048a3989d44002b99e43ec9804d4f8c1195e391e8827db0467c36636"

[[files]]
file = "config/yosbr/config/firstperson.json"
hash = "3ccd2259d9e7f97880c85c09e87f5a7fc9c3cb61c43baecb4a7b7cf45efe115a"

[[files]]
file = "config/yosbr/config/flashback/flashback.json"
hash = "907892e5b78dc879fc92415104e755844ebad9e30229c60bc55fa744128d4284"

[[files]]
file = "config/yosbr/config/freecam.json5"
hash = "8f700c032a3bbd6c411a9ff942766b93c29f8c42df14f7f3ee888448a9fdabaf"

[[files]]
file = "config/yosbr/config/ias.json"
hash = "6b1c783de370977eb7fc9a99b032c3f30bc0ced4459bfa357743753a1c4aae92"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "6367cdbdf94f763c39e54cb7cd9ce5592064f9103e01fb1e8f51b56212ee75b1"

[[files]]
file = "config/yosbr/config/lighty/base.config"
hash = "09b68befbdae4e308a1fa19f5c39e368a540cbd2cf33ff874af2955812912893"

[[files]]
file = "config/yosbr/config/litematica.json"
hash = "4ed0cefb309ec78e93dca0e39dae1b7918336fb6cc4471996d758ae79b05d4eb"

[[files]]
file = "config/yosbr/config/malilib.json"
hash = "2cfc7db930781229d510c028bf3aec705df05fc5a56e0d443868030b380c937f"

[[files]]
file = "config/yosbr/config/modmenu.json"
hash = "ce2ff4125f30767b97358c25aea4dcab5a52c25349a34c613de1b7598e406351"

[[files]]
file = "config/yosbr/config/pling.json"
hash = "dcd888e7755d2f0e8071b14020d7f121a507d199d9f8d59e566f108e42bc7f7d"

[[files]]
file = "config/yosbr/config/puzzle.json"
hash = "66235fd57899fb488f0e30b8a20feb3e90d93eb88f5edc0d252cf16daa2f7c91"

[[files]]
file = "config/yosbr/config/roughlyenoughitems/config.json5"
hash = "a78f47d49c1c8ad22fcd195abc2c9715324f3e209670cdebab28810dfaf18f7d"

[[files]]
file = "config/yosbr/config/shulkerboxtooltip.json5"
hash = "db85ba235510d022acd24965041a966b24ee36a319668deb8e2c867ffbae8fac"

[[files]]
file = "config/yosbr/config/sodium-extra-options.json"
hash = "159ed771788a63142f1cebc8d39e0b590bffe5bbf0a9fe69a704b00aef15cb46"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "4f70d5b1739896ebabbd4bb577bdf552921a9ed0cfc985853c9b1f876f059c93"

[[files]]
file = "config/yosbr/config/sound_physics_remastered/soundphysics.properties"
hash = "81abf065322139fbcfc666610fb3068897dbfefe46268e87476f20951a4fe010"

[[files]]
file = "config/yosbr/config/waveycapes.json"
hash = "eabdcd97e6792f21e0ebb79b58c452a690e57ddf4b65922f141b78989cd23e3e"

[[files]]
file = "config/yosbr/options.txt"
hash = "ed703b420aaa6cee730ab17ebd2a5fbefebcfcb1899273a1654e8659aa520883"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "904365e7891802e522e5a35189b7039e18f56a22ab30bd99af59b97ec4b7468e"
metafile = true

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "394030f614ec2081350023cc8f8b25f8210894bb8950da36f8364a8fe8893a6e"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "ca3ae2608987185814c118388f28057f729d866ee1abbc97f3650141d213fa35"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "ff1763afa21669a76a9ca65735944986ec4ef7a0d440b98ee2154aafa46356c8"
metafile = true

[[files]]
file = "mods/auth-me.pw.toml"
hash = "1562c21781759f538378d67275bac4497dd15b68b85d13e9c5b613a1ba46cacc"
metafile = true

[[files]]
file = "mods/better-clouds.pw.toml"
hash = "b40f32455fd3c28328d8d7df7764ab2208c101da712f739bcf30aee9ebecffbe"
metafile = true

[[files]]
file = "mods/better-mount-hud.pw.toml"
hash = "6ef53c2c4e506e111b4bd7c1bc8804a5a7dcb2f6e3b79054575e73f6ce61ee94"
metafile = true

[[files]]
file = "mods/better-stats.pw.toml"
hash = "8d24c50e86aad7649057b65c47ea5dddffa6b3aecf5bfe31f63bb40ced4973c7"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "8b1e7e1d6edd89356541f1c817f07d8cb1edc78bb5de22ad17b4adbc40ee1ee3"
metafile = true

[[files]]
file = "mods/blur-fabric.pw.toml"
hash = "0995c4e9b8b458c60c745116a3f3cdd0cf7a0b3082fa1f7d3305e1c780ae9f52"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "a8785544fb032c24853b8ed9bb15d65c30312f1ee5f7ada3e73a0350512702a0"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "a06ef129798265e0d7249426fb0ed5c506725b0460dc3dfdb975b8978480895e"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "d53b229a5588d33a8dac8682cba4371b22b2cbe2541c7129506cfbd44daaf6f8"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "d8e2eb843f684b6abe48010c4ebf3e1300bd0fe9a4132e2744757d850171f4b7"
metafile = true

[[files]]
file = "mods/coolrain.pw.toml"
hash = "70129d2d939c939fd1ff18adca8e728bd656fd2c1fc25485df197191e61ed8cd"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "93a6e53150e1d3b84b4fd08c01658617ad174c24d1b5afcc5b9e9e16888d7eb9"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "982801b4473e11e6f8c5899f18a260515239dfce397c650c6920fc6ae03f6abb"
metafile = true

[[files]]
file = "mods/cull-leaves.pw.toml"
hash = "0864206f0e936f9ae32ada59a90284d6b9262434c99d8c32a1fafe2b501de0cf"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "b32453041250975ffba451f0258eb91de9fa991e2a320fe36c6eafcb1c5742b7"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "7a304e1dd8fdc4ab7fb695e661547ceb951b1aa4a20ae397852c64a3d9408683"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "c23a1be7641341478b09c5c4f835b5e024a246f9e8521e92905bcab0d0e8cce0"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "d2551922e217952f0bcc574427916b2c3f8e27b145532a2469f407285004b596"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "45abf05e1cc90006aeb65e4e1bbe97da5a1984f547ea8028a077dae68af0ac11"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "408151861cc1b1a4c4e9c8a3550662a2fc36d0ea96ee07b7e96c5d2a6afacf6f"
metafile = true

[[files]]
file = "mods/fabrishot.pw.toml"
hash = "fcdaaad3ac86edfe8b2dd506b9e1303c70636251fc275f21f7a4a2efa324a8e8"
metafile = true

[[files]]
file = "mods/fadeless.pw.toml"
hash = "33751edd5b63fdc4d8c51e19a74013efc600807ad8cf773d1512072b97c8ecd7"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
hash = "c698766bdbac77ecb3ea9b9bb832cd625f6cf04f60fa0df851a5737bdffa8268"
metafile = true

[[files]]
file = "mods/fast-ip-ping.pw.toml"
hash = "8d7ef7b445497ca578dcc1c672299e497901ba41b1297515e5888af354dbd846"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "816b735b2ad505476201800a99f527e61b392b712b9d20ca9edcce05f412fe87"
metafile = true

[[files]]
file = "mods/first-person-model.pw.toml"
hash = "897027dd9e472fa15c6ffa2295869ecc9734c08df1279627f36c97bbdcbf2d36"
metafile = true

[[files]]
file = "mods/flashback.pw.toml"
hash = "544eaa2ff476c609cbfd4487fcdd09feda5f9208f1976bf3ceb4fbe4e3bb0e27"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "b22f1d052eee2810fda73d850dd6f425a1214965e03a5a9dada421abfe74603b"
metafile = true

[[files]]
file = "mods/freecam.pw.toml"
hash = "36d96641b73cc592988dc5cbc9749859a0d75f576196b519fe41a2c1b82e0333"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "9e7bacd24307639764f3b74ae35a562b6becf2701637b816de0eaae15ab714c0"
metafile = true

[[files]]
file = "mods/in-game-account-switcher.pw.toml"
hash = "0ece8f12019ca29ad7e657e4657f246feeeb3404a88bbeecc5d5941f883d422a"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "a36870bfbbd57ea241255c6573a4d129509f5e50dbdcaf12d3a78c57f864bbde"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "276947b1f9933ca2220a00736aba177e4034ca9a45cad9f258abf762fdb3bb0b"
metafile = true

[[files]]
file = "mods/jjelytraswap.pw.toml"
hash = "ef01b1f0ca39cb3dc1bc33ff6df9dec8895abeb2d5a17f9e84704419bbcd149d"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "8f6e0157b42ba668c0ba9aa7eff94b3b91a8f58bcd357e574d70a7b160d4337c"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "9c15d70a164a6e16b09212b6a24d097003f86bb595634a66c04b9a31dff38ff4"
metafile = true

[[files]]
file = "mods/language-reload.pw.toml"
hash = "59d092d4627a3a2c01ba0c621e0de6e09d6b7c04e1f3230cd735740c4f1ea537"
metafile = true

[[files]]
file = "mods/lighty.pw.toml"
hash = "ee1e1c01d6ee07eed1502d0bf20c89c38bddfd777a2a58e2e7d09f623f36c076"
metafile = true

[[files]]
file = "mods/litematica-printer.pw.toml"
hash = "768c36c17e7d8215085eecc29152bc04eb23ed18df6350210ee234215cbac1ae"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "590d8c454461493a6a60a6efe9a43bcb94231e7b55c7382f1aa209ad7a572f99"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "9a74f9345a91af6a0e2c1975e1dd1d26cfcae6fb072a3a0d68fd9de110ab6327"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "ad1110e02639ce1dd8afd73ca567d44fbe592c662d656fee567b6c1f7ced308d"
metafile = true

[[files]]
file = "mods/mixintrace.pw.toml"
hash = "b89656eaf7e4404d8d2c5b1e1155aae85a839939f83cab6d1b5e791412ad5f86"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "51ff93e279e03cb3cd77a5be0df777cdcd975d35b5149180d9dc724e47168c76"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "90f207724a47d6b32f45c6a53da2539f544df944709418761ec8ede01a401a47"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "e4b9192ce7f54715dde7eb682ebab23aaaac10658b1bd08ba553a5f99b0124d1"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "44f00c1a0e3d4f8717e805c30c862a597e7856472e72637800fd1a38d73fbd08"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "cd25851cbdaad2dd1957a8086ce54aa4bd3c45be75e1ba49168a54fafbd87898"
metafile = true

[[files]]
file = "mods/norefreshscroll.pw.toml"
hash = "5cee50b91adcf0ced437ce83518a88f2c743420586211a707dd35c4afbf2754f"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "00bc3af6def79868e126ea53faf06bbad004f094fc26d60e7b4a1eda067e7311"
metafile = true

[[files]]
file = "mods/obsidianui.pw.toml"
hash = "3cce60b7d7bb63fa7964074693376aee924c092f49d7e49b96ebf6d4dcdb8efc"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "08b89b53c392b5fa29198418df8598404d93c58eae40d432caed797c828adbd5"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "13369d7a10a47895f33629f000945d6bdf43f7b19a9ff1ca2ecfbc209c1ac431"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "3cbdb02ff4be022d7e0f9b82cd64a36669d5986d7ed3ddcf7bcdbacc0b1b4b2a"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
hash = "a62d7893eae9d5713dbe9c844b2bb9eba53157743c47b6e8abcbdd9075264cc9"
metafile = true

[[files]]
file = "mods/screencopy.pw.toml"
hash = "f316a724cd4c3536d386a40387942f133954f3c57a871493fb8755e78e4546f4"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "77f6ba8f063840c0d8a58bba2cedc2743d136c1d51cdd28d3506d19e167e08d5"
metafile = true

[[files]]
file = "mods/serverpingerfixer.pw.toml"
hash = "50855fdced2ad535c842825b761e62b339168b9ea158e452bdd4f6467a102645"
metafile = true

[[files]]
file = "mods/shoulder-surfing-reloaded.pw.toml"
hash = "96adacea9b10d8b45261e0d228112bde178bd9a445da4e6725eadf58c99deb54"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "842c53716951d19d2e791d45f3d6f1d3c6eab669db7bc3818c1a425282248aa1"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "c064e431015fe06786c17e18b8cfc28751a994e2ee251a357c0043a72f649403"
metafile = true

[[files]]
file = "mods/skinshuffle.pw.toml"
hash = "4bee6fc5f2fc60c10f4d01a30386aa5290ad80c4a71cd1b1035b1a692ea92862"
metafile = true

[[files]]
file = "mods/smooth-scroll.pw.toml"
hash = "8c3caeb7c006e6661782245deb0c25d7a4c1e6b29acdc35c9dd8ee25e874eb93"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "986e43ff06d2a79effec6e219aca063d7b53a98096c5f63983f23cf54c11c7e5"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "9d340481c374a20067d1748c1a4991626bce9d7812f0bdb96072cd7a15d35462"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "19f9479c1a4b9e5dee34eab19bcb54944a2044f69e58408fb85e7d1d5ce333dd"
metafile = true

[[files]]
file = "mods/stackdeobf.pw.toml"
hash = "621e56ad677649509141a20b4a4a6042ea30af69c1527153681f8f2c4cf0104b"
metafile = true

[[files]]
file = "mods/stendhal.pw.toml"
hash = "e57db38b7680dae1362aec9ca714b408ca98cc130a42abb48a63fbc3755b9a2c"
metafile = true

[[files]]
file = "mods/tcdcommons.pw.toml"
hash = "a9a12d51606befdc928f127ceff3c0b2ebaf4ca61ff80d62c1290e4d72b91ff8"
metafile = true

[[files]]
file = "mods/viafabricplus.pw.toml"
hash = "095c72f3e53174c217c4b6a8746e3e9ef51289ecb38ecb6e29db79800ff0c911"
metafile = true

[[files]]
file = "mods/wavey-capes.pw.toml"
hash = "3f5679e5212d0cb5e6700b4d13001d435e60fb9151121e01f83d9f10d296eba5"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "941777ea339a9e6c10af302decfff1e5c590fa4c2f06ffb813fbaa22c674d970"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "6f6334f336a876088431df70e2bba6ac52ca2ddeb73a4880ce88d6954b09af00"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "3ff0c2f005f2523f157b776f0e870494a8e8ec0ff77cb7e965c88b4e2090efdb"
metafile = true
